DEFAULT_PRODUCTS = [
    {
        "name": "Prakriti Chai",
        "category": "Tea Leaves",
        "price_per_unit": 400,
        "unit": "kg",
        "min_weight": 100,
        "max_weight": 5000,
        "badge": "Natural",
        "rating": "★★★★★",
        "description": "Natural and fresh - the purest chai experience with authentic flavors.",
        "image_url": "https://images.unsplash.com/photo-1563822249366-3efb23b8e0c9?w=500&q=80",
        "inventory_grams": 30000,
        "is_active": 1,
    },
    {
        "name": "Vanam Chai",
        "category": "Tea Leaves",
        "price_per_unit": 500,
        "unit": "kg",
        "min_weight": 100,
        "max_weight": 5000,
        "badge": "Forest-Grown",
        "rating": "★★★★★",
        "description": "Forest-grown richness - deep, aromatic chai with natural complexity.",
        "image_url": "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=500&q=80",
        "inventory_grams": 22000,
        "is_active": 1,
    },
    {
        "name": "Amrit Chai",
        "category": "Tea Leaves",
        "price_per_unit": 600,
        "unit": "kg",
        "min_weight": 100,
        "max_weight": 5000,
        "badge": "Premium",
        "rating": "★★★★★",
        "description": "Finest, nectar-like quality - the ultimate treasured chai blend.",
        "image_url": "https://images.unsplash.com/photo-1597318130435-95e3e4589e98?w=500&q=80",
        "inventory_grams": 18000,
        "is_active": 1,
    },
    {
        "name": "Kaju",
        "category": "Cashew Nuts",
        "price_per_unit": 1200,
        "unit": "kg",
        "min_weight": 100,
        "max_weight": 5000,
        "badge": "Handpicked",
        "rating": "★★★★★",
        "description": "Handpicked cashew nuts with premium quality and natural richness.",
        "image_url": "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=500&q=80",
        "inventory_grams": 12000,
        "is_active": 1,
    },
    {
        "name": "Elaichi",
        "category": "Elaichi",
        "price_per_unit": 500,
        "unit": "100g",
        "min_weight": 10,
        "max_weight": 1000,
        "badge": "Handpicked",
        "rating": "★★★★★",
        "description": "Handpicked and fresh - aromatic green cardamom pods for chai and cooking.",
        "image_url": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&q=80",
        "inventory_grams": 4000,
        "is_active": 1,
    },
]
